version: '3.9'

services:
    slim:
        build: ./php
        command: php -S 0.0.0.0:8080 -t public
        container_name: slim
        ports:
            - 8080:8080
        volumes:
            - .:/var/www/html
            - ./logs:/var/www/logs
            - ./php/php.ini:/usr/local/etc/php/php.ini